Add a debug line to print out syslog receiver metrics
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

diff --git a/tasks/event-acceptance/task b/tasks/event-acceptance/task
--- a/tasks/event-acceptance/task
+++ b/tasks/event-acceptance/task
@@ -62,7 +62,11 @@ function main {
 
     sleep 5
     echo "asserting on metrics received from the crosstalk receiver"
+    # Dont quit the script if fails to grep
+    set +e
     receiver_metrics="$(curl -s http://localhost:6061/metrics)"
+    set -e
+    echo $receiver_metrics | jq 'del(.memstats, .cmdline)'
     expected="1"
     result="$(echo "$receiver_metrics" | jq '.namespaced["oratos"]' --join-output)"
     check_result_cnt "$expected" "$result" \
