Finish up control plane downtime tests
[#159783067]

Signed-off-by: Robert Sullivan <rsullivan@pivotal.io>

diff --git a/pipelines/sink-resources.yml b/pipelines/sink-resources.yml
--- a/pipelines/sink-resources.yml
+++ b/pipelines/sink-resources.yml
@@ -6,8 +6,10 @@ groups:
   - build-events-controller-image
   - deploy-gke
   - deploy-cfcr
+  - deploy-control-plane
   - gke-tests
   - cfcr-tests
+  - control-plane-tests
   - promote
 - name: release
   jobs:
@@ -37,7 +39,7 @@ resources:
   type: git
   source:
     uri: https://github.com/pivotal-cf/oratos-ci
-    branch: master
+    branch: control-plane-test
 
 - name: sink-resources
   type: git
@@ -88,6 +90,15 @@ resources:
     role_id: ((vault.role_id))
     secret_id: ((vault.secret_id))
     path: secret/envs/oratos-ci-testing-cfcr-bbl-state
+    tarball: true
+
+- name: control-plane-test-bbl-state
+  type: vault
+  source:
+    url: https://vault.oratos.ci.cf-app.com
+    role_id: ((vault.role_id))
+    secret_id: ((vault.secret_id))
+    path: secret/envs/control-plane-test-bbl-state
     tarball: true
 
 - name: sink-resources-github-release
@@ -452,16 +463,19 @@ jobs:
       passed:
       - cfcr-tests
       - gke-tests
+      - control-plane-tests
     - get: sink-controller-image
       passed:
       - cfcr-tests
       - gke-tests
+      - control-plane-tests
       params:
         save: true
     - get: events-controller-image
       passed:
       - cfcr-tests
       - gke-tests
+      - control-plane-tests
       params:
         save: true
     - task: write-promote-tag
@@ -554,13 +568,13 @@ jobs:
 
             mount -o remount,rw /sys/fs/cgroup
 
-            sed -e 1d /proc/cgroups | while read sys hierarchy num enabled; do
+            sed -e 1d /proc/cgroups | while read -r sys _ _ enabled; do
               if [ "$enabled" != "1" ]; then
                 # subsystem disabled; skip
                 continue
               fi
 
-              grouping="$(cat /proc/self/cgroup | cut -d: -f2 | grep "\\<$sys\\>")" || true
+              grouping="$(cut -d: -f2 /proc/self/cgroup | grep "\\<$sys\\>")" || true
               if [ -z "$grouping" ]; then
                 # subsystem not mounted anywhere; mount it on its own
                 grouping="$sys"
@@ -709,7 +723,7 @@ jobs:
     passed:
     - release
     version:
-      tag: *release_params_version
+      tag: ((sink_resource_release_params.VERSION))
   - get: sink-resources-release
   - get: oratos-ci
   - task: update-bosh-release
@@ -729,3 +743,164 @@ jobs:
       tag: bosh-release/tag
       globs:
       - bosh-release/binaries/*.tgz
+
+- name: deploy-control-plane
+  serial: true
+  plan:
+  - aggregate:
+    - get: sink-resources
+      trigger: true
+      passed:
+      - build-sink-controller-image
+      - build-events-controller-image
+    - get: sink-controller-image
+      trigger: true
+      passed:
+      - build-sink-controller-image
+      params:
+        skip_download: true
+    - get: events-controller-image
+      trigger: true
+      passed:
+      - build-events-controller-image
+      params:
+        skip_download: true
+    - get: control-plane-test-bbl-state
+    - get: oratos-ci
+  - task: deploy
+    input_mapping:
+      bbl-state: control-plane-test-bbl-state
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: oratos/ci-base
+      inputs:
+      - name: sink-resources
+      - name: sink-controller-image
+      - name: events-controller-image
+      - name: oratos-ci
+      - name: bbl-state
+      params:
+        DEBUG:
+      run:
+        path: /bin/bash
+        args:
+        - "-c"
+        - |
+          #!/bin/bash
+          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x
+
+          BBL_STATE_DIR=bbl-state \
+              oratos-ci/scripts/cfcr.sh control-plane-test get-credentials
+
+          sha="$(cat sink-controller-image/tag)"
+          yq read sink-resources/manifests/60-deployments/sink.yml --tojson | \
+            jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$sha"'"' \
+            > sink-resources/manifests/60-deployments/sink.json
+          rm sink-resources/manifests/60-deployments/sink.yml
+
+          events_sha="$(cat events-controller-image/tag)"
+          yq read sink-resources/manifests/60-deployments/events.yml --tojson | \
+            jq '(.spec.template.spec.containers[] | select(.name == "events-controller")).image = "oratos/events-controller:'"$events_sha"'"' \
+            > sink-resources/manifests/60-deployments/events.json
+          rm sink-resources/manifests/60-deployments/events.yml
+
+          kubectl apply -R -f sink-resources/manifests
+          patch='{"spec": {"template": {"metadata": {"labels": {"randomversion": "'$RANDOM'"}}}}}'
+          kubectl patch -R -f sink-resources/manifests --patch "$patch"
+
+- name: control-plane-tests
+  plan:
+  - aggregate:
+    - get: sink-resources
+      trigger: true
+      passed:
+      - deploy-control-plane
+    - get: sink-controller-image
+      trigger: true
+      passed:
+      - deploy-control-plane
+    - get: events-controller-image
+      trigger: true
+      passed:
+      - deploy-control-plane
+      params:
+        skip_download: true
+    - get: control-plane-test-bbl-state
+    - get: oratos-ci
+  - task: run-test
+    input_mapping:
+      bbl-state: control-plane-test-bbl-state
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: oratos/ci-base
+      inputs:
+      - name: bbl-state
+      - name: oratos-ci
+      params:
+        DEBUG:
+      run:
+        path: /bin/bash
+        args:
+        - "-c"
+        - |
+          #!/bin/bash
+          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x
+
+          source "oratos-ci/scripts/test/common.sh"
+
+          function clean_up {
+            bosh -d cfcr start master -n
+
+            sleep 60
+            kubectl delete --filename oratos-ci/tools/logspewer/manifest/deployment.yml
+            kubectl delete pod crosstalk-receiver-oratos
+
+            set +e
+            killall -9 kubectl > /dev/null 2>&1 # clean up port forwarding
+          }
+
+          # set bosh env vars
+          set +x
+          pushd bbl-state/bbl-state > /dev/null
+            eval "$(bbl print-env)"
+          popd > /dev/null
+          set -x
+
+          BBL_STATE_DIR=bbl-state \
+            oratos-ci/scripts/cfcr.sh control-plane-test get-credentials
+
+          # cleanup test state
+          trap clean_up EXIT
+
+          # create crosstalk-receiver pod
+          apply_crosstalk_receiver oratos
+
+          # create sink connected to crosstalk-receiver
+          apply_namespace_sink oratos
+
+          # create emitter
+          kubectl apply --filename oratos-ci/tools/logspewer/manifests/deployment.yml
+
+          # set up port forward to receiver
+          kubectl --namespace oratos port-forward crosstalk-receiver-oratos 6060:6060 > /dev/null 2>&1 &
+          sleep 5 # ensure port forwarding is active
+
+          # verify receiver is receiving logs
+          assert_log_count_gt 0 oratos
+
+          # stop control plane
+          bosh --deployment cfcr stop master --non-interactive
+          sleep 10 # wait for master to stop
+
+          # get base count
+          count="$(assert_log_count_gt 0 oratos)"
+
+          # verify receiver is still receiving logs
+          sleep 10 # wait for logs to build up
+          assert_log_count_gt "$count" oratos
