Poll for loadbalancer IP in order to communicate with crosstalk-receiver /metrics

diff --git a/pipelines/sink-resources.yml b/pipelines/sink-resources.yml
--- a/pipelines/sink-resources.yml
+++ b/pipelines/sink-resources.yml
@@ -855,16 +855,18 @@ jobs:
           source "oratos-ci/scripts/test/common.sh"
 
           function clean_up {
-            bosh --deployment cfcr start master --non-interactive
+            bosh \
+              --deployment cfcr \
+              ssh master -c 'if [ -e /tmp/iptables.orig ]; then sudo iptables-restore /tmp/iptables.orig; sudo rm /tmp/iptables.orig; fi'
 
-            sleep 30
-            kubectl delete \
-              --namespace oratos \
-              --filename oratos-ci/tools/logspewer/manifests/deployment.yml
-            kubectl delete pod crosstalk-receiver-oratos --namespace default
-
+            sleep 10
             set +e
-            killall -9 kubectl > /dev/null 2>&1 # clean up port forwarding
+            kubectl delete \
+              --filename oratos-ci/tools/logspewer/manifests/deployment.yml \
+              --namespace oratos
+            kubectl delete service crosstalk-receiver-oratos \
+              --namespace default
+            kubectl delete pod crosstalk-receiver-oratos --namespace default
           }
 
           # set bosh env vars
@@ -891,23 +893,37 @@ jobs:
             --filename oratos-ci/tools/logspewer/manifests/deployment.yml \
             --namespace oratos
 
-          # set up port forward to receiver
-          sleep 15 # ensure receiver pod is running
-          kubectl \
-            --namespace default \
-            port-forward crosstalk-receiver-oratos 6061:6061 &
-          sleep 15 # ensure port forwarding is active
+          # poll for crosstalk-receiver lb ip address
+          count=1
+          echo -n "polling for lb ip address"
+          while true; do
+              echo -n .
+              ip="$(kubectl get service crosstalk-receiver-oratos \
+                      --namespace default \
+                      --output json \
+                      | jq .status.loadBalancer.ingress[0].ip --join-output)"
+              if [ "$ip" != "null" ] && [ "$ip" != "" ]; then
+                  break
+              fi
+              if [ "$count" -gt 30 ]; then
+                  echo "unable to get service lb ip address"
+                  exit 1
+              fi
+              sleep 5
+              ((count++))
+          done
 
           # verify receiver is receiving logs
-          assert_log_count_gt 0 oratos
+          assert_log_count_gt 0 oratos "$ip"
 
-          # stop control plane
-          bosh --deployment cfcr stop master --non-interactive
-          sleep 10 # wait for master to stop
+          # "stop" control plane
+          bosh \
+            --deployment cfcr \
+            ssh master -c 'sudo iptables-save > /tmp/iptables.orig; sudo iptables -A INPUT -p tcp --dport 8080 -j DROP; sudo iptables -A INPUT -p tcp --dport 8443 -j DROP'
 
           # get base count
-          count="$(assert_log_count_gt 0 oratos)"
+          count="$(assert_log_count_gt 0 oratos "$ip")"
 
           # verify receiver is still receiving logs
           sleep 10 # wait for logs to build up
-          assert_log_count_gt "$count" oratos
+          assert_log_count_gt "$count" oratos "$ip"
