Set DNS record when we get lb ip
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

diff --git a/pipelines/testing-clusters.yml b/pipelines/testing-clusters.yml
--- a/pipelines/testing-clusters.yml
+++ b/pipelines/testing-clusters.yml
@@ -284,7 +284,7 @@ jobs:
       - name: oratos-ci-testing-cfcr-bbl-state
       - name: oratos-ci
       outputs:
-      - name: modified-kubo-deployment
+      - name: lb-ip
       params:
         DEBUG:
       run:
@@ -306,7 +306,78 @@ jobs:
               oratos-ci/scripts/cfcr.sh testing get-credentials-tunnel
 
           patch='{"spec": {"type": "LoadBalancer"}}'
-          kubectl patch service kubernetes --namespace default --patch "$patch" || true
+          kubectl patch service kubernetes \
+              --namespace default \
+              --patch "$patch" \
+              || true
+
+          count=1
+          echo -n "polling for lb ip address"
+          while true; do
+              echo -n .
+              ip="$(kubectl get service kubernetes \
+                      --namespace default \
+                      --output json \
+                      | jq .status.loadBalancer.ingress[0].ip --join-output)"
+              if [ "$ip" != "null" ] && [ "$ip" != "" ]; then
+                  break
+              fi
+              if [ "$count" -gt 30 ]; then
+                  echo "unable to get service lb ip address"
+                  exit 1
+              fi
+              sleep 5
+              ((count++))
+          done
+          echo "$ip" > lb-ip/ip
+  - task: configure-dns
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: mesosphere/aws-cli
+      inputs:
+      - name: lb-ip
+      params:
+        AWS_ACCESS_KEY_ID: ((aws.dev_dns_access_key_id))
+        AWS_SECRET_ACCESS_KEY: ((aws.dev_dns_secret_access_key))
+        ENV_DNS_NAME: testing-cfcr.oratos.ci.cf-app.com.
+        DEBUG:
+      run:
+        path: /bin/sh
+        args:
+        - "-c"
+        - |
+          #!/bin/sh
+          set -euo pipefail; [ -n "$DEBUG" ] && set -x
+
+          ip="$(cat lb-ip/ip)"
+
+          cat > /tmp/payload <<EOF
+          {
+            "Comment": "update DNS record for cfcr cluster with load balancer ip",
+            "Changes": [
+              {
+                "Action": "UPSERT",
+                "ResourceRecordSet": {
+                  "Name": "$ENV_DNS_NAME",
+                  "Type": "A",
+                  "TTL": 60,
+                  "ResourceRecords": [
+                    {
+                      "Value": "$ip"
+                    }
+                  ]
+                }
+              }
+            ]
+          }
+          EOF
+          payload="$(cat /tmp/payload)"
+          aws route53 change-resource-record-sets \
+              --hosted-zone-id /hostedzone/Z15MCPBTYDBNBO \
+              --change-batch "$payload"
 
 - name: oratos-ci-testing-cfcr-destroy
   serial_groups:
