Guard from exiting the script if grep returns non-zero
grep returns exit code 1 if it cannot find the message in the file

[#159026029]

diff --git a/tasks/k8s-blackbox/task b/tasks/k8s-blackbox/task
--- a/tasks/k8s-blackbox/task
+++ b/tasks/k8s-blackbox/task
@@ -149,7 +149,10 @@ curl "http://localhost:8080?cycles=$CYCLES&delay=$DELAY$DELAY_UNIT&text=$MESSAGE
 
 sleep "$WAIT" # wait for a bit to collect logs
 
+# Dont quit the script if fails to grep
+set +e
 MSG_COUNT=$(grep -c "$MESSAGE" output.txt)
+set -e
 
 if [ "$MSG_COUNT" -lt $(($CYCLES * 99 / 100)) ]; then
     echo the reliability test did not meet our SLO
diff --git a/tasks/k8s-fluentbit-blackbox/task b/tasks/k8s-fluentbit-blackbox/task
--- a/tasks/k8s-fluentbit-blackbox/task
+++ b/tasks/k8s-fluentbit-blackbox/task
@@ -139,7 +139,10 @@ sleep "$WAIT" # wait for a bit to collect logs
 echo "Collecting logs for $logspinner_pod_name"
 papertrail --min-time '30 minutes ago' "$MESSAGE" > output.txt
 
+# Dont quit the script if fails to grep
+set +e
 MSG_COUNT=$(grep -c "$MESSAGE" output.txt)
+set -e
 
 echo "The number of messages received: $MSG_COUNT"
 echo "The number of messages sent    : $CYCLES"
